In [1]:
import json
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Source Codes (Human)

In [13]:
source_code_path = "./../Datasets/Humans/Cleaned/"
df = pd.DataFrame()

HumanDFs = []

# for p in os.listdir(source_code_path):
#     if p.endswith(".csv"):
#         df = pd.concat([df, pd.read_csv(source_code_path + p)])

for p in os.listdir(source_code_path):
    if p.endswith(".csv"):
        HumanDFs.append(pd.read_csv(source_code_path + p))

In [14]:
CombinedHumanDF = pd.DataFrame()
for df in HumanDFs:
    CombinedHumanDF = pd.concat([CombinedHumanDF,df])
CombinedHumanDF

,writer,problem_id,submission_id,website,source
0,human,NaN,12746065.0,https://codeforces.com,/*\n******************************************...
1,human,NaN,12746876.0,https://codeforces.com,#include<iostream>\n\nusing namespace std;\n\n...
2,human,NaN,12747297.0,https://codeforces.com,#include <iostream>\n#include <sstream>\n#incl...
3,human,NaN,12747301.0,https://codeforces.com,#include<stdio.h>\n#include<algorithm>\n#inclu...
4,human,NaN,12747302.0,https://codeforces.com,#include <bits/stdc++.h>\nusing namespace std;...
...,...,...,...,...,...
990,Human,NaN,NaN,https://programming.in.th,#include<bits/stdc++.h>\n#define sz(x) (int)(x...
991,Human,NaN,NaN,https://programming.in.th,#include <bits/stdc++.h>\n\nusing namespace st...
992,Human,NaN,NaN,https://programming.in.th,#include <bits/stdc++.h>\n\nusing namespace st...
993,Human,NaN,NaN,https://programming.in.th,"#include ""equal.h""\n#include <bits/stdc++.h>\n..."
994,Human,NaN,NaN,https://programming.in.th,#include <bits/stdc++.h>\n\nusing namespace st...

In [15]:
CombinedHumanDF['submission_id'] = pd.to_numeric(CombinedHumanDF['submission_id'], errors='coerce').astype('Int64')
CombinedHumanDF

,writer,problem_id,submission_id,website,source
0,human,NaN,12746065,https://codeforces.com,/*\n******************************************...
1,human,NaN,12746876,https://codeforces.com,#include<iostream>\n\nusing namespace std;\n\n...
2,human,NaN,12747297,https://codeforces.com,#include <iostream>\n#include <sstream>\n#incl...
3,human,NaN,12747301,https://codeforces.com,#include<stdio.h>\n#include<algorithm>\n#inclu...
4,human,NaN,12747302,https://codeforces.com,#include <bits/stdc++.h>\nusing namespace std;...
...,...,...,...,...,...
990,Human,NaN,<NA>,https://programming.in.th,#include<bits/stdc++.h>\n#define sz(x) (int)(x...
991,Human,NaN,<NA>,https://programming.in.th,#include <bits/stdc++.h>\n\nusing namespace st...
992,Human,NaN,<NA>,https://programming.in.th,#include <bits/stdc++.h>\n\nusing namespace st...
993,Human,NaN,<NA>,https://programming.in.th,"#include ""equal.h""\n#include <bits/stdc++.h>\n..."
994,Human,NaN,<NA>,https://programming.in.th,#include <bits/stdc++.h>\n\nusing namespace st...

## Load Source Codes (AI)

In [16]:
source_code_path = "./../datasets/AI-Generated/Cleaned/"
df = pd.DataFrame()

AIDFs = []

for p in os.listdir(source_code_path):
    if p.endswith(".csv"):
        AIDFs.append(pd.read_csv(source_code_path + p))
    
AIDFs[0]

,writer,problem_id,submission_id,website,source
0,AI,1991A,NaN,https://codeforces.com,#include <bits/stdc++.h>\nusing namespace std;...
1,AI,1991A,NaN,https://codeforces.com,#include <iostream>\n#include <vector>\n\nusin...
2,AI,1991A,NaN,https://codeforces.com,#include <iostream>\n#include <vector>\n\nusin...
3,AI,1991A,NaN,https://codeforces.com,#include <iostream>\n#include <vector>\n#inclu...
4,AI,1991A,NaN,https://codeforces.com,#include <iostream>\n#include <vector>\n\nusin...
...,...,...,...,...,...
47775,AI,1115U2,NaN,https://codeforces.com,#include <iostream>\nusing namespace std;\n\ni...
47776,AI,1115U2,NaN,https://codeforces.com,#include <iostream>\n#include <bitset>\n\nusin...
47777,AI,1115U2,NaN,https://codeforces.com,#include <vector>\n\nusing namespace std;\n\nc...
47778,AI,1115U2,NaN,https://codeforces.com,#include <Quantum>\n\nnamespace Quantum.Kata.U...
47779,AI,1115U2,NaN,https://codeforces.com,#include <iostream>\n#include <cmath>\nusing n...

In [17]:
CombinedAIDF = pd.DataFrame()
for df in AIDFs:
    CombinedAIDF = pd.concat([CombinedAIDF,df])
CombinedAIDF

,writer,problem_id,submission_id,website,source,Unnamed: 0
0,AI,1991A,NaN,https://codeforces.com,#include <bits/stdc++.h>\nusing namespace std;...,NaN
1,AI,1991A,NaN,https://codeforces.com,#include <iostream>\n#include <vector>\n\nusin...,NaN
2,AI,1991A,NaN,https://codeforces.com,#include <iostream>\n#include <vector>\n\nusin...,NaN
3,AI,1991A,NaN,https://codeforces.com,#include <iostream>\n#include <vector>\n#inclu...,NaN
4,AI,1991A,NaN,https://codeforces.com,#include <iostream>\n#include <vector>\n\nusin...,NaN
...,...,...,...,...,...,...
1336,AI,tumso20_penguin2,NaN,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...,2078.0
1337,AI,tumso20_shibuyajihen2,NaN,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...,2079.0
1338,AI,tumso20_simplepotatolanguage,NaN,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...,2080.0
1339,AI,tumso20_space2,NaN,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...,2081.0
1340,AI,tumso20_tetrisbattle2,NaN,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...,2082.0

In [18]:
CombinedAIDF['submission_id'] = pd.to_numeric(CombinedAIDF['submission_id'], errors='coerce').astype('Int64')
CombinedAIDF

,writer,problem_id,submission_id,website,source,Unnamed: 0
0,AI,1991A,<NA>,https://codeforces.com,#include <bits/stdc++.h>\nusing namespace std;...,NaN
1,AI,1991A,<NA>,https://codeforces.com,#include <iostream>\n#include <vector>\n\nusin...,NaN
2,AI,1991A,<NA>,https://codeforces.com,#include <iostream>\n#include <vector>\n\nusin...,NaN
3,AI,1991A,<NA>,https://codeforces.com,#include <iostream>\n#include <vector>\n#inclu...,NaN
4,AI,1991A,<NA>,https://codeforces.com,#include <iostream>\n#include <vector>\n\nusin...,NaN
...,...,...,...,...,...,...
1336,AI,tumso20_penguin2,<NA>,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...,2078.0
1337,AI,tumso20_shibuyajihen2,<NA>,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...,2079.0
1338,AI,tumso20_simplepotatolanguage,<NA>,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...,2080.0
1339,AI,tumso20_space2,<NA>,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...,2081.0
1340,AI,tumso20_tetrisbattle2,<NA>,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...,2082.0

## Clean NAN

In [19]:
CombinedHumanDF = CombinedHumanDF[~CombinedHumanDF['source'].isna()]
CombinedAIDF = CombinedAIDF[~CombinedAIDF['source'].isna()]

## Clean Duplicate

In [22]:
CombinedAIDF = CombinedAIDF[~CombinedAIDF['source'].duplicated(keep='first')]
CombinedHumanDF = CombinedHumanDF[~CombinedHumanDF['source'].duplicated(keep='first')]

In [32]:
CombinedAIDF.to_csv('./combined/AI.csv')
CombinedHumanDF.to_csv('./combined/Human.csv')

## View Data

In [30]:
CombinedHumanDF['website'].value_counts() , CombinedAIDF['website'].value_counts()

(website
 https://codeforces.com       1061136
 https://programming.in.th      16658
 https://firefly.gchan.moe       1636
 Name: count, dtype: int64,
 website
 https://codeforces.com       45526
 https://programming.in.th     1341
 https://firefly.gchan.moe      714
 Name: count, dtype: int64)

In [ ]:
CombinedHumanDF = CombinedHumanDF[~CombinedHumanDF['source'].duplicated(keep='first')]
CombinedAIDF = CombinedAIDF[~CombinedAIDF['source'].duplicated(keep='first')]

In [11]:
HumanSampled_df = (CombinedHumanDF[CombinedHumanDF['website'] == 'https://codeforces.com']).sample(n=500, random_state=42)
HumanSampled_df = pd.concat([HumanSampled_df,(CombinedHumanDF[CombinedHumanDF['website'] == 'https://programming.in.th']).sample(n=500, random_state=37)])
HumanSampled_df = pd.concat([HumanSampled_df,(CombinedHumanDF[CombinedHumanDF['website'] == 'https://firefly.gchan.moe']).sample(n=500, random_state=37)])

In [12]:
AISampled_df = (CombinedAIDF[CombinedAIDF['website'] == 'https://codeforces.com']).sample(n=500, random_state=42)
AISampled_df = pd.concat([AISampled_df,(CombinedAIDF[CombinedAIDF['website'] == 'https://programming.in.th']).sample(n=500, random_state=37)])
AISampled_df = pd.concat([AISampled_df,(CombinedAIDF[CombinedAIDF['website'] == 'https://firefly.gchan.moe']).sample(n=500, random_state=37)])

In [14]:
MixSampled_df = pd.concat([AISampled_df,HumanSampled_df])
MixSampled_df = MixSampled_df.sample(frac=1, random_state=82).reset_index(drop=True)

In [15]:
AISampled_df.to_csv('./example_test/AI.csv')
HumanSampled_df.to_csv('./example_test/Human.csv')
MixSampled_df.to_csv('./example_test/Mixed.csv')