In [2]:
import pandas as pd
import glob
import os

## Programming.in.th

In [50]:
csv_dir = './programmin/'
csv_files = glob.glob(os.path.join(csv_dir, '*.csv'))

df = pd.concat([pd.read_csv(file) for file in csv_files], ignore_index=True)
df

,SubmissionID,ProblemURL,Score,Language,Source,User
0,130000,toi17_1221,30 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
1,130001,toi17_1221,35 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
2,130002,0019,14 points,C,"#include<stdio.h>\nint findmin(int s,int b){\n...",Papp kun
3,130003,toi17_1221,45 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
4,130004,toi17_1221,45 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
...,...,...,...,...,...,...
73375,212996,0004,0 points,Python 3,T = str(input())\n if T == T.upper () :\n pri...,pattarapol lampurypol
73376,212997,0004,0 points,Python 3,F = str(input())\nif F == F.upper () :\nprint(...,ธัญญ์ชรัศ กรมราช
73377,212998,0009,100 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,Dessert
73378,212999,0004,0 points,Python 3,F = str(input())\nif F == F.upper () :\nprint(...,ธัญญ์ชรัศ กรมราช
73379,213000,0004,0 points,Python 3,T = str(input())\n if T == T.upper () :\n p...,pattarapol lampurypol

In [51]:
# Remove all non-cpp files
df = df[df['Language']=="C++"]
df

,SubmissionID,ProblemURL,Score,Language,Source,User
0,130000,toi17_1221,30 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
1,130001,toi17_1221,35 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
3,130003,toi17_1221,45 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
4,130004,toi17_1221,45 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
5,130005,1000,100 points,C++,#include <iostream>\n\n\nusing namespace std;\...,pattadon
...,...,...,...,...,...,...
73365,212986,0002,0 points,C++,#include<iostream>\nusing namespace std;\nmain...,Ananya Buarahong
73368,212989,0002,90 points,C++,#include<iostream>\nusing namespace std;\nmain...,Ananya Buarahong
73370,212991,0002,100 points,C++,#include<iostream>\nusing namespace std;\nmain...,Ananya Buarahong
73374,212995,0011,100 points,C++,#include<bits/stdc++.h>\nusing namespace std;\...,MEEMANAIIZ
73377,212998,0009,100 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,Dessert

In [52]:
# Remove all 0 point
df = df[df['Score']!='0 points']
df

,SubmissionID,ProblemURL,Score,Language,Source,User
0,130000,toi17_1221,30 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
1,130001,toi17_1221,35 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
3,130003,toi17_1221,45 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
4,130004,toi17_1221,45 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
5,130005,1000,100 points,C++,#include <iostream>\n\n\nusing namespace std;\...,pattadon
...,...,...,...,...,...,...
73362,212983,0001,100 points,C++,#include<iostream>\nusing namespace std;\nmain...,Ananya Buarahong
73368,212989,0002,90 points,C++,#include<iostream>\nusing namespace std;\nmain...,Ananya Buarahong
73370,212991,0002,100 points,C++,#include<iostream>\nusing namespace std;\nmain...,Ananya Buarahong
73374,212995,0011,100 points,C++,#include<bits/stdc++.h>\nusing namespace std;\...,MEEMANAIIZ
73377,212998,0009,100 points,C++,#include <bits/stdc++.h>\nusing namespace std;...,Dessert

In [53]:
# Remove 0000 , 0001 , 0002 ... 0005 , codecube_001 codecube_002
df = df[~df['ProblemURL'].isin([
    "0000", "0001", "0002", "0003", "0004", "0005",
    "codecube_001", "codecube_002"
])]

df['ProblemURL'].value_counts()

ProblemURL
toi11_place              679
toi11_labor              646
toi11_candle             462
toi12_peak               416
toi19_energy             416
                        ...
o60_may08_expensive        1
o66_oct_c2_sumproduct      1
codecube_206               1
codecube_131               1
codecube_034               1
Name: count, Length: 568, dtype: int64

In [54]:
df['Score'] = df['Score'].str.extract(r'(\d+)').astype(int)

C:\Users\Pakin\AppData\Local\Temp\ipykernel_13464\3633118867.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Score'] = df['Score'].str.extract(r'(\d+)').astype(int)

In [55]:
# Check TOI Problems
df[df['ProblemURL'].str.contains('toi', case=False, na=False)]

,SubmissionID,ProblemURL,Score,Language,Source,User
0,130000,toi17_1221,30,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
1,130001,toi17_1221,35,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
3,130003,toi17_1221,45,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
4,130004,toi17_1221,45,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
6,130006,toi17_1221,100,C++,#include <bits/stdc++.h>\nusing namespace std;...,โอ้ย พี่จ๋า
...,...,...,...,...,...,...
73318,212939,toi11_labor,85,C++,#include<bits/stdc++.h>\n\n\nusing namespace s...,กะเพราหมูกรอบ
73320,212941,toi11_labor,85,C++,#include<bits/stdc++.h>\nusing namespace std;\...,กะเพราหมูกรอบ
73321,212942,toi11_labor,85,C++,#include<bits/stdc++.h>\nusing namespace std;\...,กะเพราหมูกรอบ
73322,212943,toi11_labor,65,C++,#include<bits/stdc++.h>\nusing namespace std;\...,กะเพราหมูกรอบ
73323,212944,toi11_labor,100,C++,#include<bits/stdc++.h>\nusing namespace std;\...,กะเพราหมูกรอบ

Label with writer,problem_id,submission_id,website,source (human, - , - , https://programming.in.th/ , -)

In [56]:
df = df.drop_duplicates(subset='Source',keep='last')

In [57]:
df = df.sort_values('Score', ascending=False)
df = df.drop_duplicates(subset=['User', 'ProblemURL'], keep='first')

In [58]:
df

,SubmissionID,ProblemURL,Score,Language,Source,User
66497,175595,tumso20_disaster2,250,C++,#include<bits/stdc++.h>\n#define sz(x) (int)(x...,ttamx
66500,175598,tumso20_space2,250,C++,#include<bits/stdc++.h>\n#define sz(x) (int)(x...,ttamx
22514,304572,tumso20_disaster2,250,C++,#include <bits/stdc++.h>\n#define int long lon...,Namkhing
66509,175607,tumso20_shop2,162,C++,#include<bits/stdc++.h>\n\n\nusing namespace s...,ttamx
61418,170505,tumso20_drilling,150,C++,#include<bits/stdc++.h>\n\n\nusing namespace s...,Blackslex
...,...,...,...,...,...,...
22124,304182,toi12_peak,5,C++,#include<bits/stdc++.h>\nusing namespace std;\...,Nay-O
19144,301202,toi1_roman,4,C++,#include <bits/stdc++.h>\nusing namespace std;...,real นาย ณัฐฎัทร ปัทมะทิน
58034,166118,cnc_2206_multiverse,4,C++,#include<bits/stdc++.h>\nusing namespace std;\...,JP.
42063,324135,2014,4,C++,#include<bits/stdc++.h>\nusing namespace std;\...,Snow Aurora (WINTER)
9999,51009,1002,4,C++,#include <iostream>\n#include <cmath>\nusing n...,เหวิน

In [59]:
df['User'].value_counts()[:15]

User
ℕ𝕠𝕧𝕖𝕞ℕ𝕠𝕥𝕖𝕤        117
gnippihsananab    115
pridelique        105
mrtbts            103
Blackslex          95
MiyaZaki           94
JungPS             86
ppp                85
KanapojPM          80
aO(m)s1n           79
FdaviNmuFvwv#@     76
Kantegral          76
JP.                76
sn00py2304         75
ฟรีด้อมม           74
Name: count, dtype: int64

In [60]:
cleaned_df = pd.DataFrame()

cleaned_df['problem_id'] = df['ProblemURL']
cleaned_df['submission_id'] = df['SubmissionID']
cleaned_df['source'] = df['Source']
cleaned_df['writer'] = "human"
cleaned_df['website'] = "https://programming.in.th"
cleaned_df = cleaned_df[['writer','problem_id','submission_id','website','source']]
cleaned_df

,writer,problem_id,submission_id,website,source
66497,human,tumso20_disaster2,175595,https://programming.in.th,#include<bits/stdc++.h>\n#define sz(x) (int)(x...
66500,human,tumso20_space2,175598,https://programming.in.th,#include<bits/stdc++.h>\n#define sz(x) (int)(x...
22514,human,tumso20_disaster2,304572,https://programming.in.th,#include <bits/stdc++.h>\n#define int long lon...
66509,human,tumso20_shop2,175607,https://programming.in.th,#include<bits/stdc++.h>\n\n\nusing namespace s...
61418,human,tumso20_drilling,170505,https://programming.in.th,#include<bits/stdc++.h>\n\n\nusing namespace s...
...,...,...,...,...,...
22124,human,toi12_peak,304182,https://programming.in.th,#include<bits/stdc++.h>\nusing namespace std;\...
19144,human,toi1_roman,301202,https://programming.in.th,#include <bits/stdc++.h>\nusing namespace std;...
58034,human,cnc_2206_multiverse,166118,https://programming.in.th,#include<bits/stdc++.h>\nusing namespace std;\...
42063,human,2014,324135,https://programming.in.th,#include<bits/stdc++.h>\nusing namespace std;\...
9999,human,1002,51009,https://programming.in.th,#include <iostream>\n#include <cmath>\nusing n...

In [61]:
cleaned_df.to_csv('./cleaned/programmingin1.csv',index=False)

## Grader Chan

In [62]:
df = pd.read_csv('./graderchan_source.csv')
df

,User,SubmissionID,ProblemURL,Score,Language,Source
0,User: Winkrittapas2550gmail.com,17,/problemset/watch_vtuber,Score: 0,Language: cpp,#include<bits/stdc++.h>\nusing namespace std ;...
1,User: Nathlol,18,/problemset/watch_vtuber,Score: 70,Language: c,"#include <stdio.h>\n\nint main(){\n int x, ..."
2,User: Nathlol,19,/problemset/watch_vtuber,Score: 70,Language: c,"#include <stdio.h>\n\nint main(){\n int x, ..."
3,User: Winkrittapas2550gmail.com,20,/problemset/watch_vtuber,Score: 0,Language: cpp,#include<bits/stdc++.h>\nusing namespace std ;...
4,User: foldnut,21,/problemset/watch_vtuber,Score: 100,Language: c,#include <stdio.h>\n#include <math.h>\n#includ...
...,...,...,...,...,...,...
4929,User: NovemNotes,5047,/problemset/ice_cream,Score: 24,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4930,User: NovemNotes,5048,/problemset/ice_cream,Score: 0,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4931,User: NovemNotes,5049,/problemset/ice_cream,Score: 29,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4932,User: NovemNotes,5050,/problemset/ice_cream,Score: 21,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4933,User: NovemNotes,5051,/problemset/ice_cream,Score: 0,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."

In [63]:
df = df[(df['Language'] == "Language: cpp")]
df

,User,SubmissionID,ProblemURL,Score,Language,Source
0,User: Winkrittapas2550gmail.com,17,/problemset/watch_vtuber,Score: 0,Language: cpp,#include<bits/stdc++.h>\nusing namespace std ;...
3,User: Winkrittapas2550gmail.com,20,/problemset/watch_vtuber,Score: 0,Language: cpp,#include<bits/stdc++.h>\nusing namespace std ;...
9,User: Winkrittapas2550gmail.com,26,/problemset/watch_vtuber,Score: 100,Language: cpp,#include<bits/stdc++.h>\nusing namespace std ;...
15,User: admin,32,/problemset/amogus,Score: 100,Language: cpp,#include <stdio.h>\n\nint main() {\n\tint n;\n...
16,User: admin,33,/problemset/factor,Score: 100,Language: cpp,#include <stdio.h>\n\nint main() {\n\tint n;\n...
...,...,...,...,...,...,...
4929,User: NovemNotes,5047,/problemset/ice_cream,Score: 24,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4930,User: NovemNotes,5048,/problemset/ice_cream,Score: 0,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4931,User: NovemNotes,5049,/problemset/ice_cream,Score: 29,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4932,User: NovemNotes,5050,/problemset/ice_cream,Score: 21,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4933,User: NovemNotes,5051,/problemset/ice_cream,Score: 0,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."

In [64]:
df = df[df['Score'] != "Score: 0"]
df

,User,SubmissionID,ProblemURL,Score,Language,Source
9,User: Winkrittapas2550gmail.com,26,/problemset/watch_vtuber,Score: 100,Language: cpp,#include<bits/stdc++.h>\nusing namespace std ;...
15,User: admin,32,/problemset/amogus,Score: 100,Language: cpp,#include <stdio.h>\n\nint main() {\n\tint n;\n...
16,User: admin,33,/problemset/factor,Score: 100,Language: cpp,#include <stdio.h>\n\nint main() {\n\tint n;\n...
17,User: admin,34,/problemset/harbour_cruise,Score: 100,Language: cpp,"#include <stdio.h>\n\nint s[5005], e[5005];\ni..."
18,User: admin,35,/problemset/traveller,Score: 100,Language: cpp,#include <stdio.h>\n\nchar c(int x) {\n\tif (0...
...,...,...,...,...,...,...
4923,User: njoop,5041,/problemset/ice_cream,Score: 69,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4927,User: NovemNotes,5045,/problemset/ice_cream,Score: 29,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4929,User: NovemNotes,5047,/problemset/ice_cream,Score: 24,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4931,User: NovemNotes,5049,/problemset/ice_cream,Score: 29,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."
4932,User: NovemNotes,5050,/problemset/ice_cream,Score: 21,Language: cpp,"#include ""ice_cream.h""\n\nint guess(int n) {\n..."

In [66]:
df['Score'] = df['Score'].str.extract(r'Score:\s*(\d+)').astype(int)

C:\Users\Pakin\AppData\Local\Temp\ipykernel_13464\2972185441.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Score'] = df['Score'].str.extract(r'Score:\s*(\d+)').astype(int)

In [68]:
df = df.drop_duplicates(subset='Source',keep='last')

In [70]:
df = df.sort_values('Score', ascending=False)
df = df.drop_duplicates(subset=['User', 'ProblemURL'], keep='first')

In [73]:
df['User'].value_counts()[:20]

User
User: njoop               67
User: Dormon              61
User: Monasm              52
User: Winzzwz             48
User: Nathlol2            43
User: Namkhing            42
User: admin               35
User: hmmm                31
User: Cmoss9              29
User: pxsit               28
User: Pera                25
User: Newtonabc           23
User: Ecir                22
User: mydKN               22
User: Nagornz             22
User: qwerty              22
User: detectives_conan    18
User: Nightingale         18
User: fluke               17
User: FotoFatTurtle       17
Name: count, dtype: int64

In [74]:
cleaned_df = pd.DataFrame()

cleaned_df['problem_id'] = df['ProblemURL']
cleaned_df['submission_id'] = df['SubmissionID']
cleaned_df['source'] = df['Source']
cleaned_df['writer'] = "human"
cleaned_df['website'] = "https://firefly.gchan.moe"
cleaned_df = cleaned_df[['writer','problem_id','submission_id','website','source']]
cleaned_df

,writer,problem_id,submission_id,website,source
4804,human,/problemset/c2_su65_chocolate,4922,https://firefly.gchan.moe,#include <bits/stdc++.h>\nusing namespace std;...
2987,human,/problemset/c2_su65_chocolate,3091,https://firefly.gchan.moe,/*\n Author : detective conan\n Problem ...
3194,human,/problemset/c2_su65_chocolate,3298,https://firefly.gchan.moe,/*\n author : PakinDioxide\n created : ...
3272,human,/problemset/c2_su65_chocolate,3376,https://firefly.gchan.moe,"#pragma GCC optimize(""Ofast,no-stack-protector..."
3153,human,/problemset/c2_su65_chocolate,3257,https://firefly.gchan.moe,// YoruoniVamp - VTUBE\n// Pragma Credit to Di...
...,...,...,...,...,...
3290,human,/problemset/range_sum_medium,3394,https://firefly.gchan.moe,#include <bits/stdc++.h>\nusing namespace std;...
1784,human,/problemset/range_sum_hard,1854,https://firefly.gchan.moe,#include <bits/stdc++.h>\nusing namespace std;...
703,human,/problemset/range_sum_medium,721,https://firefly.gchan.moe,#include <stdio.h>\n\nint main() {\n int N;...
4122,human,/problemset/range_sum_medium,4226,https://firefly.gchan.moe,#include <bits/stdc++.h>\nusing namespace std;...
2304,human,/problemset/range_sum_medium,2393,https://firefly.gchan.moe,#include <bits/stdc++.h>\nusing namespace std;...

In [75]:
cleaned_df.to_csv('./cleaned/graderchan1.csv',index=False)